install:
  # proselint
  - sudo pip install proselint
  # markdown-link-check
  - sudo apt-get install npm
  - sudo npm install -g markdown-link-check

script: 
  # Check dead links
  - find . -name \*.md -exec markdown-link-check {} \; 2>/dev/null | egrep "[✖]"
  # proselint
  - proselint README.md
